### ISSUE TITLE
Mod_Proxy with haproxy

### ISSUE THREAD

**Issue by cdenneen** [Castaglia/proftpd-mod_proxy#1]
Do you know if mod_proxy supports proxy-pass from haproxy or if not will it as FR?

Thanks

**Comment by Castaglia** [comment]
In conjunction with using mod_proxy_protocol for the *receiving* side, you can use mod_proxy option for using the PROXY protocol on the *sending* side:

    ProxyOptions UseProxyProtocol

With this combination, then, I'm considering this issue as addressed.  Please reopen if this is not the case.  Thanks!
