### ISSUE TITLE
mod_proxy does not build with older (e.g. 3.6.x) SQLite versions

### ISSUE THREAD

**Issue by GermanoGuerrini** [Castaglia/proftpd-mod_proxy#106]
Hello,

I'm trying to compile proftp with proftpd-mod_proxy on Centos 6.6.
I cloned both repositories using the master branch:

proftpd:
`# git show --oneline -s`
`bda6daf Merge pull request #452 from proftpd/logfmt-remote-port-bug4296`

proftpd-mod_proxy
`# git show --oneline -s`
`ade27e8 Merge pull request #102 from Castaglia/use-datastore`

The `./configure --with-modules mod_proxy` returns:
`--------------`
`Build Summary`
`--------------`
`Building the following static modules:`
`  mod_ident`
`  mod_proxy`
`  mod_cap`

`--------------`

When I finally make it, this is what I get:

```
make[2]: Entering directory `/opt/proftpd/contrib/mod_proxy'
gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include  -g2 -O2 -Wall -fno-omit-frame-pointer -c mod_proxy.c -o mod_proxy.o
gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include  -g2 -O2 -Wall -fno-omit-frame-pointer -c lib/proxy/random.c -o lib/proxy/random.o
gcc  -DHAVE_CONFIG_H  -DLINUX  -I. -I./include -I../.. -I../../include  -g2 -O2 -Wall -fno-omit-frame-pointer -c lib/proxy/db.c -o lib/proxy/db.o
lib/proxy/db.c: In function ‘proxy_db_exec_prepared_stmt’:
lib/proxy/db.c:435: warning: implicit declaration of function ‘sqlite3_stmt_readonly’
lib/proxy/db.c: In function ‘proxy_db_init’:
lib/proxy/db.c:898: error: ‘SQLITE_CONFIG_LOG’ undeclared (first use in this function)
lib/proxy/db.c:898: error: (Each undeclared identifier is reported only once
lib/proxy/db.c:898: error: for each function it appears in.)
make[2]: *** [lib/proxy/db.o] Error 1
make[2]: Leaving directory `/opt/proftpd/contrib/mod_proxy'
make[1]: *** [static] Error 2
make[1]: Leaving directory `/opt/proftpd/modules'
make: *** [modules] Error 2
```

The developer headers for sqlite are installed:

```
# yum list installed | grep sqlite-devel.x86_64
sqlite-devel.x86_64                      3.6.20-1.el6_7.2            @updates
```

Is there anything else I can check?

PS: I also tried to compile against tag v0.3, but I got another error:
```
contrib/mod_proxy/mod_proxy.a(db.o): In function `proxy_db_exec_prepared_stmt':
/opt/proftpd/contrib/mod_proxy/lib/proxy/db.c:312: undefined reference to `sqlite3_stmt_readonly'
collect2: ld returned 1 exit status
make: *** [proftpd] Error 1
```

Thanks a lot!

**Comment by Castaglia** [comment]
This should now be fixed in master.  The code should now build; you may have to try it out to ensure that it _runs_ as expected with the older SQLite version.
