### ISSUE TITLE
SQL-provided backend servers not properly used when using Redis ProxyDatastore

### ISSUE THREAD

**Issue by tomsommer** [Castaglia/proftpd-mod_proxy#110]
I have ProxyDatastore set to redis, and using data from mod_sql for ProxyReverseServers.

Once mod_sql returns data, it is cached in Redis and never leaves this cache? If I change the data/backend in SQL, the change is not picked up. How do you disable or control this cache?

**Comment by Castaglia** [comment]
Redis is not being used as a "cache", it is being used as a persistent datastore.

To help me reproduce the behavior you're seeing, could you provide the full mod_proxy config you're using, the values that you are are changing in your SQL table, etc?

**Comment by tomsommer** [comment]
I'm changing the 'url' value as per the documentation example, but this redis-command is done on every login: 
`"LRANGE" "ftp1proxy_reverse:PerUser:vhost#1" "0" "-1"`
Which returns the old url-backend?


```
SQLAuthenticate Off
SQLBackend mysql
SQLConnectInfo XXXXXXXXXXXXXXX
SQLNamedQuery get-user-servers SELECT "backend FROM proxy WHERE username = '%{0}'"

ProxyEngine on
ProxyTLSEngine off
ProxyDatastore Redis ftp1
ProxyOptions ShowFeatures
ProxyTables /var/proftpd
ProxySourceAddress XXXXXXXX
ProxyRole reverse
ProxyReverseConnectPolicy PerUser
ProxyReverseServers sql:/get-user-servers
```

**Comment by Castaglia** [comment]
Per my local reproduction recipes, this is now fixed in master.

**Comment by tomsommer** [comment]
Thank you
