### ISSUE TITLE
failed to initialize Redis datastore

### ISSUE THREAD

**Issue by skirmis** [Castaglia/proftpd-mod_proxy#112]
Are mod_proxy ready for use with Redis backend?

Error:
`mod_redis/0.1: using hiredis-0.12.1   
mod_proxy/0.5: error opening Redis connection: Function not implemented    
mod_proxy/0.5: failed to initialize Redis datastore: No such file or directory    
mod_proxy/0.5: unable to initialize reverse proxy, failing to start up: No such file or directory
`

ProFTPD Version 1.3.6rc5   
Compiled-in modules:
  mod_core.c
  mod_sql.c
  mod_sql_mysql.c
  mod_tls.c
  mod_redis.c

Config:
RedisEngine			on
RedisServer 			127.0.0.1:6379
ProxyEngine                     on
ProxyRole                       reverse
ProxyReverseConnectPolicy       PerUser
ProxyDatastore 			Redis proxy:

....

config is good for ProxyDatastore: sqlite

Thank you

**Comment by Castaglia** [comment]
The Redis support requires the latest ProFTPD source code from GitHub; the RC release does not have it.  In addition, you must compile ProFTPD with the `--enable-redis` configure option to enable it...

**Comment by Castaglia** [comment]
That's a typo (now fixed) in the `mod_redis` documentation.

After re-building ProFTPD with `--enable-redis`, did you _also_ recompile `mod_proxy`?   Or is it from a previously installed DSO/shared module installation?

**Comment by skirmis** [comment]
Yes, I have did. I did not use DSO/shared module installation

**Comment by Castaglia** [comment]
Hrm.  Perhaps you can give me a reproduction recipe, of the all the steps (downloading, configuring, etc), so that I can reproduce this issue locally?
