### ISSUE TITLE
ip_len variable clashes with ip_len definition in netinet/ip.h

### ISSUE THREAD

**Issue by ws0w** [Castaglia/proftpd-mod_proxy#115]
I ran into a problem on AIX 7.1 compiling the latest mod_proxy code with proftpd-1.3.6 ... the error message was baffling because it referred to a symbol not referenced anywhere in the mod_proxy code. 

The error message was in mod_proxy/lib/proxy/reverse/db.c  -- the variable ip_len clashes with a symbol defined in /usr/include/netinet/ip.h

I resolved the problem by changing 'ip_len' to 'ip_length' in db.c

I don't know where this is specific to AIX, or if it can happen on other platforms.

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!
