### ISSUE TITLE
ProxyReverseConnectPolicy PerUser allow only one connection.

### ISSUE THREAD

**Issue by cschang2** [Castaglia/proftpd-mod_proxy#120]
proftpd version: 1.3.6-stable

First connection working well, but when I try to create second ftp connection the FTP client show error:

> Connection failed.
> PASS: Operation not permitted
>

ProxyLog show sqlite database is locked

> error executing 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked:
> error executing 'SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = ? AND user_name = ?;': unknown error
> error preparing database for ProxyReverseConnectPolicy PerUser for user 'ftpuser': No such file or directory
> error selecting backend server: Operation not permitted
>

Dump sqlite database show proxy_vhost_reverse_per_user have duplicate records.

> CREATE TABLE proxy_vhosts (vhost_id INTEGER NOT NULL PRIMARY KEY, vhost_name TEXT NOT NULL);
> INSERT INTO proxy_vhosts VALUES(1,'ProFTPD');
> CREATE TABLE proxy_vhost_reverse_per_user (vhost_id INTEGER NOT NULL, user_name TEXT NOT NULL, backend_uri TEXT, FOREIGN KEY (vhost_id) REFERENCES proxy_vhosts (vhost_id));
> INSERT INTO proxy_vhost_reverse_per_user VALUES(1,'ftpuser','ftp://ftpuser:ftppwd@www.ftp.server:21');
> INSERT INTO proxy_vhost_reverse_per_user VALUES(1,'ftpuser','ftp://ftpuser:ftppwd@www.ftp.server:21');
> INSERT INTO proxy_vhost_reverse_per_user VALUES(1,'ftpuser','ftp://ftpuser:ftppwd@www.ftp.server:21');
> INSERT INTO proxy_vhost_reverse_per_user VALUES(1,'ftpuser','ftp://ftpuser:ftppwd@www.ftp.server:21');
> INSERT INTO proxy_vhost_reverse_per_user VALUES(1,'ftpuser','ftp://ftpuser:ftppwd@www.ftp.server:21');
> INSERT INTO proxy_vhost_reverse_per_user VALUES(1,'ftpuser2','ftp://ftpuser2:ftppwd2@www.ftp.server2:21');
> 

proftpd.conf 

> SQLNamedQuery get-user-servers SELECT "url FROM proxy_user_servers WHERE user_name = '%{0}'"
> <IfModule mod_proxy.c>
>     ProxyEngine on
>     ProxyLog /var/log/proxy.log
>     ProxyTables /var/ftp/proxy
>     ProxyRole reverse
>     # Make sure to authenticate in the proxy itself
>     ProxyOptions UseReverseProxyAuth
>     ProxyReverseConnectPolicy PerUser
>     ProxyReverseServers sql:/get-user-servers
> </IfModule>
>

**Comment by Castaglia** [comment]
Which version of `mod_proxy` are you using?

**Comment by Castaglia** [comment]
This sounds similar to Issue #93 and to Issue #98, which is why I'm wondering if you are using an older `mod_proxy` version.

**Comment by cschang2** [comment]
#define MOD_PROXY_VERSION       "mod_proxy/0.5"

**Comment by cschang2** [comment]
Below is ProxyLog and TraceLog at the same logfile.

> [5783] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (1, 'ftpserver1', 'ftp://ftpserver1:ftppwd1@www.ftpserver1:21');
> [5783] <proxy.db:13>: successfully executed 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);'
> mod_proxy/0.5[5783]: selected backend server 'ftp://ftpserver1:ftppwd1@www.ftpserver1:21'
> mod_proxy/0.5[5783]: received banner from backend 192.168.15.11:21: 220 FTP Server ready.
> [5783] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': SELECT COUNT(*) FROM proxy_vhost_reverse_per_user;
> [5783] <proxy.db:2>: error executing 'SELECT COUNT(*) FROM proxy_vhost_reverse_per_user;': unknown error
> mod_proxy/0.5[5783]: error executing 'SELECT COUNT(*) FROM proxy_vhost_reverse_per_user;': unknown error
> mod_proxy/0.5[5783]: error updating database for backend server index -1: Operation not permitted
> [5783] <proxy:9>: chrooted session to '/var/ftp/proxy/empty'
> mod_proxy/0.5[5783]: proxy session running as UID 0, GID 0, restricted to '/var/ftp/proxy/empty'
> [5783] <proxy:15>: found group 'NONE' for command 'CLNT'
> [5783] <proxy:15>: found group 'NONE' for command 'OPTS'
> [5783] <proxy:15>: found group 'NONE' for command 'TYPE'
> mod_proxy/0.5[5783]: Entering Passive Mode (192,168,15,15,192,49).
> [5783] <proxy:17>: connecting to backend server for passive data transfer for MLSD
> mod_proxy/0.5[5783]: passive backend data connection opened - local  : 192.168.15.15:54177
> mod_proxy/0.5[5783]: passive backend data connection opened - remote : 192.168.15.11:49219
> [5783] <proxy:17>: accepting connection from frontend client for passive data transfer for MLSD
> mod_proxy/0.5[5783]: passive frontend data connection opened - local  : 192.168.15.15:49201
> mod_proxy/0.5[5783]: passive frontend data connection opened - remote : 192.168.15.136:49959
> [5783] <proxy:19>: handling data connection during data transfer
> [5783] <proxy:9>: received 1448 bytes of data from source data connection
> [5783] <proxy:19>: handling data connection during data transfer
> [5783] <proxy:9>: received 1448 bytes of data from source data connection
> [5783] <proxy:19>: handling data connection during data transfer
> [5783] <proxy:9>: received 1448 bytes of data from source data connection
> [5783] <proxy:19>: handling data connection during data transfer
> [5783] <proxy:9>: received 1362 bytes of data from source data connection
> [5783] <proxy:19>: handling data connection during data transfer
> [5783] <proxy:19>: read EOF on data connection, closing frontend/backend data connections
> [5784] <proxy.db:19>: attempting to open proxy_reverse tables at path '/var/ftp/proxy/proxy-reverse.db'
> [5784] <proxy.db:1>: (sqlite3): [error 28] attempt to open "/var/ftp/proxy/proxy-reverse.db" as file descriptor 2
> [5784] <proxy.db:10>: schema 'proxy_reverse': executing statement 'PRAGMA temp_store = MEMORY;'
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': PRAGMA temp_store = MEMORY;
> [5784] <proxy.db:13>: successfully executed 'PRAGMA temp_store = MEMORY;'
> [5784] <proxy.db:10>: schema 'proxy_reverse': executing statement 'PRAGMA journal_mode = MEMORY;'
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': PRAGMA journal_mode = MEMORY;
> [5784] <proxy.db:9>: results for 'PRAGMA journal_mode = MEMORY;':
> [5784] <proxy.db:9>: col #1 [journal_mode]: memory
> [5784] <proxy.db:13>: successfully executed 'PRAGMA journal_mode = MEMORY;'
> [5784] <proxy.db:9>: opened SQLite table '/var/ftp/proxy/proxy-reverse.db'
> [5784] <proxy:9>: removed PRE_CMD APPE mod_xfer handlers
> [5784] <proxy:9>: removed PRE_CMD RETR mod_xfer handlers
> [5784] <proxy:9>: removed PRE_CMD STOR mod_xfer handlers
> [5784] <proxy:9>: removed PRE_CMD STOU mod_xfer handlers
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (1, 'ftpserver2', 'ftp://ftpserver2:ftppwd2@www.ftpserver2:21');
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 0, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 1, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 2, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 3, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 4, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 5, retry = false
> [5784] <proxy.db:2>: error executing 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked
> mod_proxy/0.5[5784]: error executing 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked:
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = 1 AND user_name = 'ftpserver2';
> [5784] <proxy.db:13>: successfully executed 'SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = ? AND user_name = ?;'
> mod_proxy/0.5[5784]: error preparing database for ProxyReverseConnectPolicy PerUser for user 'ftpserver2': No such file or directory
> mod_proxy/0.5[5784]: error selecting backend server: Operation not permitted
> [5784] <proxy.db:3>: error resetting prepared statement 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = 1 AND user_name = 'ftpserver2';
> [5784] <proxy.db:13>: successfully executed 'SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = ? AND user_name = ?;'
> mod_proxy/0.5[5784]: error preparing database for ProxyReverseConnectPolicy PerUser for user 'ftpserver2': No such file or directory
> mod_proxy/0.5[5784]: error selecting backend server: Operation not permitted
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (1, 'ftpserver2', 'ftp://ftpserver2:ftppwd2@www.ftpserver2:21');
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 0, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 1, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 2, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 3, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 4, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 5, retry = false
> [5784] <proxy.db:2>: error executing 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked
> mod_proxy/0.5[5784]: error executing 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked:
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = 1 AND user_name = 'ftpserver2';
> [5784] <proxy.db:13>: successfully executed 'SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = ? AND user_name = ?;'
> mod_proxy/0.5[5784]: error preparing database for ProxyReverseConnectPolicy PerUser for user 'ftpserver2': No such file or directory
> mod_proxy/0.5[5784]: error selecting backend server: Operation not permitted
> [5784] <proxy.db:3>: error resetting prepared statement 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = 1 AND user_name = 'ftpserver2';
> [5784] <proxy.db:13>: successfully executed 'SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = ? AND user_name = ?;'
> mod_proxy/0.5[5784]: error preparing database for ProxyReverseConnectPolicy PerUser for user 'ftpserver2': No such file or directory
> mod_proxy/0.5[5784]: error selecting backend server: Operation not permitted
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (1, 'ftpserver2', 'ftp://ftpserver2:ftppwd2@www.ftpserver2:21');
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 0, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 1, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 2, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 3, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 4, retry = true
> [5784] <proxy.db:1>: (sqlite3): schema 'proxy_reverse': busy count = 5, retry = false
> [5784] <proxy.db:2>: error executing 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked
> mod_proxy/0.5[5784]: error executing 'INSERT INTO proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked:
> [5784] <proxy.db:17>: (sqlite3): schema 'proxy_reverse': SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = 1 AND user_name = 'ftpserver2';
> [5784] <proxy.db:13>: successfully executed 'SELECT backend_uri FROM proxy_vhost_reverse_per_user WHERE vhost_id = ? AND user_name = ?;'
> mod_proxy/0.5[5784]: error preparing database for ProxyReverseConnectPolicy PerUser for user 'ftpserver2': No such file or directory
> mod_proxy/0.5[5784]: error selecting backend server: Operation not permitted
> mod_proxy/0.5[5784]: ProxyRetryCount 5 reached with no successful connection, failing
>

**Comment by cschang2** [comment]
Upgrade sqlite from 3.6.20 to 3.20.0 fixed this problem.

**Comment by Castaglia** [comment]
Interesting!  Thanks for that update.  I will add something along these lines to the `mod_proxy` docs.

When developing/testing locally, it looks like I'm using SQLite 3.8.5.  And for newer features, I use SQLite 3.17.0.  I'll go through the SQLite release notes, to see if something between 3.6.20 and 3.8.5 might be related to the behavior you saw.

Is `mod_proxy` now working well for you?

**Comment by cschang2** [comment]
Proftpd+mod_proxy development and production server both works well. Thank you.

**Comment by Castaglia** [comment]
Great!  Considering this as addressed.
