### ISSUE TITLE
Forward proxy not sending PROT P command?

### ISSUE THREAD

**Issue by grahampea** [Castaglia/proftpd-mod_proxy#136]
Good morning,
I have built proftpd-1.3.6 with mod_proxy 0.4, and have successfully configured this as a reverse proxy providing FTPS->FTP.  When I connect with lftp with everything configured for FTPS, I see lftp issues PBSZ 0 and PROT P commands, and the data connection is then secured. I can see the corresponding packets in a wireshark capture as well, and all is good.
I have then tried to configure another instance of my built proftpd as a forward proxy. It successfully establishes a TLSv1 connection with the reverse proxy. But the forward proxy never appears to issue a PROT P (or PBSZ 0) command before any LIST command, and the reverse proxy denies the LIST:

` 2018-09-26 08:19:33,788 mod_tls/2.7[32403]: SSL/TLS required but absent on data channel, denying LIST command`

I thought that this would be controlled in the forward proxy configuration with:
ProxyTLSTransferProtectionPolicy          required
But setting to 'client' or 'required' doesn't seem to change anything.

Any clues much appreciated.

```
./proftpd -l
Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
  mod_dso.c
  mod_ident.c
  mod_tls.c
  mod_proxy.c
  mod_cap.c

./proftpd -V
Compile-time Settings:
  Version: 1.3.6 (stable)
  Platform: LINUX [Linux 4.9.0-4-amd64 x86_64]
  Built: Wed Sep 19 2018 11:42:45 BST
  Built With:
    configure  '--enable-openssl' '--enable-dso' '--with-modules=mod_tls:mod_proxy'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer
  LDFLAGS: -L$(top_srcdir)/lib  -rdynamic
  LIBS:  -lssl -lcrypto -L$(top_srcdir)/lib/libcap -lcap  -lssl -lcrypto  -lsqlite3 -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard
    Header Directory:
      /usr/local/include/proftpd
    Shared Module Directory:
      /usr/local/libexec

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    - curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    - NLS support
    - Redis support
    - Sodium support
    + OpenSSL support
    - PCRE support
    - POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

```

I attach my forward proxy configuration.

[proftpd.conf.txt](https://github.com/Castaglia/proftpd-mod_proxy/files/2419041/proftpd.conf.txt)

**Comment by Castaglia** [comment]
Would you be able to provide a session transcript, showing the order of the FTP commands used by your client, from connect through `PROT P`, when `mod_proxy` is configured as a forward proxy?  I'd like to double-check the state machine in `mod_proxy`, and make sure it's doing the right thing -- and the state machine is a bit sensitive (unfortunately at present) to the ordering of those commands, especially with regard to `USER` and `PASS`.

**Comment by Castaglia** [comment]
If the latest `mod_proxy` code works as you need, and there's nothing more to add to this ticket, I'd like to close it.

**Comment by Castaglia** [comment]
I was able to verify, finally, that the above commit worked, to appropriately proxy the `PROT P` command from the client to a backend server, when `mod_proxy` is configured for forward proxying:
```
2020-04-08 03:23:59,364 [36] <proxy.ftp.ctrl:9>: proxied command 'PROT P' from f
rontend to backend
2020-04-08 03:23:59,548 [36] <proxy.ftp.ctrl:9>: received '200 PROT command succ
essful.' response from backend to frontend
```
