### ISSUE TITLE
Vsftpd backend says "DATA connection terminated without SSL shutdown."

### ISSUE THREAD

**Issue by tinuzz** [Castaglia/proftpd-mod_proxy#142]
Hi, I'm using current master of mod_proxy with ProFTPD 1.3.6 on a Debian server. This is my first attempt at setting up an FTP reverse proxy with this software.

I'm proxying to a Vsftpd backend over TLS. For the most part, this seems to work fine, meaning a TLS session is established and I can retrieve data. However, when I try to upload a file, I get an error. The Vsftpd server says:

`"DATA connection terminated without SSL shutdown. Buggy client! Integrity of upload cannot be asserted."`

and subsequently sends a "426 Failure reading network stream." response to mod_proxy, which relays it to my client (FileZilla), which in turn retries the upload a couple of times.

Could this be a bug in mod_proxy, or is it something in my configuration that's not right?

My config is this:

      <IfModule mod_proxy.c>
         ProxyEngine on
         ProxyLog /var/log/proftpd/proxy.log
         ProxyTables /var/lib/proftpd/proxy

         ProxyRole reverse
         ProxyReverseConnectPolicy RoundRobin
         ProxyReverseServers ftp://remotehost.iawsm.nl:21
         ProxyDataTransferPolicy passive

         ProxyTLSOptions EnableDiags
         ProxyTLSProtocol TLSv1.2
         ProxyTLSTransferProtectionPolicy required
    </IfModule>`

Thanks,
Martijn.

**Comment by Castaglia** [comment]
Apologies for the long delay; my development machine needed to be fixed.

I suspect it's an implementation issue in `mod_proxy`, at least at first glance.  I'll see if I can reproduce this issue locally, and get more data.

**Comment by tinuzz** [comment]
Great! Even though I have no use for an FTP reverse proxy at the moment, it is good to know that there are options. Let me know if there's anything I can do to help.

**Comment by Castaglia** [comment]
At long last, I was able to reproduce this locally, and find and fix the issue.  `mod_proxy` should now be doing the right thing in `master`.

**Comment by tinuzz** [comment]
Good to hear! Thanks!
