### ISSUE TITLE
Support SRV record lookup for reverse pool

### ISSUE THREAD

**Issue by wasabii** [Castaglia/proftpd-mod_proxy#144]
It would be nice if `ProxyReverseServers` would respect SRV records for retrieving sets of backend servers, and their relative weights.

My backend FTP server lives in an application management framework which advertises the current node the service is on (or nodes) using SRV records. As the service moves (cluster changes size, re-balancing) the service is moved from one node to another. It would be nice if I could just point mod_proxy at the hostname for the service, and have it figure out the backends on its own.

**Comment by Castaglia** [comment]
Can you provide an example of the `SRV` records that your framework publishes?  Thanks!

**Comment by wasabii** [comment]
So, I want to give you something like `_ftp._tcp.name`, however, it looks like the specific framework I'm using ignores `_ftp._tcp` and just uses `name`. Which is pretty non-standard. And I wouldn't recommend you implement it.

However, it also publishes the records in TXT records in `ftp://host:port/` format. As well as multiple A records in preference order.

So, lots of choices here.

**Comment by Castaglia** [comment]
Agreed.  Have an internal timer/thread to re-poll for resolved IP addresses for a given DNS name for a backend server seems desirable, even necessary.

**Comment by wasabii** [comment]
For more context, HAProxy supports this. But, it's insufficient for FTP. You gotta do both control and data connections independently. And it's not too easy to get them affinitized.

```
backend ftp
    balance roundrobin
    server-template ftp 5 ftp.example.local:21 check resolvers mydns init-addr none
```

It will continually update the `ftp` backend with new servers as they come and go. And will do failover between them, order them however you see fit, etc.

**Comment by Castaglia** [comment]
I should note that `mod_proxy` _does_ currently resolve a given DNS name to its multiple `A` and/or `AAAA` records; this resolution happens per frontend connection.  And when attempting to connect to the IP addresses in these records, `mod_proxy` will cycle through the returned list, until a connection succeeds (or all records have been tried).

So the scope of this feature request will be for supporting DNS resolution for `TXT` and/or `SRV` records.

For `TXT` DNS records, it sounds like we would need to attempt discovery via `TXT` records first; if found, parse those `TXT` records for URLs, and then resolve the DNS names in those URLs.

For `SRV` records, I'll see how HAproxy implements them.

**Comment by wasabii** [comment]
Hmm. It doesn't retreat l treat then as a pool though? As in, a set of independent backends, with health status, etc. That is, of one goes down, give up on it for awhile.

**Comment by Castaglia** [comment]
No, `mod_proxy` does not currently do any asynchronous probes/healthchecks of configured backend servers, no tracking of state of such probes/checks.

**Comment by wasabii** [comment]
Yeah, so, no proactive health checks, I get that. But let's say it tries for a frontend connection. Does it try again for the next one?

**Comment by Castaglia** [comment]
Yes, since a new, different frontend connection from a client creates a new process, and there is no guarantee on when that second frontend connection will occur.  It could be immediately, it could be hours/days later.

**Comment by Castaglia** [comment]
I've opened https://github.com/Castaglia/proftpd-mod_proxy/issues/186 for the feature of passively tracking backend server availability.

**Comment by Castaglia** [comment]
@wasabii I've been working on this recently, and have something almost ready to merge.  However, before I do so, I wanted to clarify whether you had "DNS service discovery", specifically [RFC 6763: DNS-SD](https://tools.ietf.org/html/rfc6763), in mind for this?  I'm currently double-checking if what I've implemented matches/follows that RFC (or not)...

**Comment by wasabii** [comment]
Actually, no. The DNS-SD specification describes how `<instance>.<service>` prefixes are added automatically so that certain protocols can be auto discovered. For instance, a FTP client might accept user into of `foo.com`, and instead query for `_ftp._tcp.foo.com`. This is useful for client devices, as it prevents them from having to know the exact service name: `ftp.foo.com`. But, it's not too useful for reverse proxies or other backend services, that are already aware of the existence of the service and whom only need to determine priority of endpoints to connect to.

Take HAProxy's configuration, for example:

```
backend ftp
    balance roundrobin
    server-template ftp 5 _ftp._tcp.example.local:21 check resolvers mydns init-addr none
```
Notice how `server-template` explicitly specifies `_ftp._tcp`. It does not (and does not support) inserting `_ftp._tcp` into the template, since the user of the reverse proxy is quite aware of what FQDN to fetch SRV records from.

The same applies to HTTP reverse proxies (such as NGINX): https://www.nginx.com/blog/dns-service-discovery-nginx-plus/#:~:text=Using%20SRV%20Records%20with%20NGINX,services%20are%20often%20dynamically%20assigned.

Even in NGINX, you have to explicitly specific the `servicename` parameter:

```
server backends.example.com service=_http._tcp resolve;
```

I would ask that ProFTPD function the same: don't get smart and try to auto add `_ftp._tcp`. Just let the user specific the FQDN of the record: and just issue a query for SRV records to that record. There is no guarantee that any specific DNS framework will even use such service names, nor what they will be.

**Comment by wasabii** [comment]
You are correctly using 2782 instead of 6763. DNS-SD is some weird PTR record lookup thing for enumerating available services. But not necessarily how to handle them once you find them.

In the case of a reverse proxy, we know there are backend services. The administrator knows. That's why he's setting up the proxy to begin with.

One thing I would add though is do not specifically prepend `_ftp._tcp` automatically. Let the user specify the FQDN of the hostname at which to issue the SRV query. Not all orchestration frameworks use `<service>.<instance>` notation. Some are just naked names. This would be similar to how HAProxy and NGINX operate.

HAProxy requires you to configure the FQDN:

```
backend ftp
    balance roundrobin
    server-template ftp 5 _ftp._tcp.example.local:21 check resolvers mydns init-addr none
```

And NGINX is similar:

```
server backends.example.com service=_http._tcp resolve;
```

This allows flexibility to use the 'standard' service.instance name, or pick your own.

**Comment by Castaglia** [comment]
Makes sense -- thanks for that input, @wasabii .

You also mentioned support for `TXT` records; what format/data would you have in mind, for these `TXT` records?

**Comment by wasabii** [comment]
Url format.  ftp://host

**Comment by Castaglia** [comment]
@wasabii I've just merged support for this; let me know what you think.

The way I've implemented it, you can use _e.g._:
```
# Discover backend servers via DNS SRV records
ProxyReverseServers ftp+srv://_ftp._tcp.example.com

# Discover backend servers via DNS TXT records
ProxyReverseServers ftp+txt://example.com
```
These SRV/TXT URL scheme variants also apply to FTPS URLs.

**Comment by wasabii** [comment]
Hmm. The notation is a bit odd, but I don't see anything wrong with it. It's been awhile since I've worked on this. Over a year and a half, actually, so I no longer have access to the code base I was building that could use it. But, I'll see about trying to test it out.

**Comment by Castaglia** [comment]
@wasabii Understood.  I'd appreciate any feedback you have on this, when you get time to work on it.  In the mean time, I'll close this ticket; we'll use new tickets for any issues that come up.  Thanks!
