### ISSUE TITLE
Behavior if fallback server is missing

### ISSUE THREAD

**Issue by sc911** [Castaglia/proftpd-mod_proxy#148]
I'm using the following proxy config:
```
ProxyEngine on
ProxyLog /var/proftpd/proxy.log
ProxyReverseConnectPolicy PerUser
ProxyReverseServers file:/var/proftpd/backend/%U.json
ProxyRole reverse
ProxyTables /var/proftpd/proxytables
```
So user based backends without any fallback backends, as those wouldn't make sense in this configuration. 

Now when someone tries to login with wrong credentials there is a different error code on a wrong password and a wrong username :
```
220 ProFTPD Server (...) [x.x.x.x]
USER xyz
331 Password required for xyz
PASS ****************
530 Login or password incorrect!
```
```
220 ProFTPD Server (...) [x.x.x.x]
USER abc
500 USER: Operation not permitted
```
From a security point of view this is no optimal. An attacker should not get any hints, what is wrong.
From a users view this is confusing, as there is nothing telling him it's about the credentials he entered.
From a technical point this is correct: 500 for an server side permanent negative completion.

I could solve this by an additional ftp-server denying all credentials and configuring mod_proxy to use this server as fallback. But this seems a bit of an overkill to me.

What I could think of would be an option to configure the behavior when there is no server found when `ProxyReverseConnectPolicy PerUser` is set. Allowing to choose between a server error (500) or an authentication error (530) would be great!

I know, getting only a 500 instead of an segfault on this kind of configuration is already an improvement and I am very grateful for that! (https://github.com/Castaglia/proftpd-mod_proxy/issues/61)

Thanks for your effort!

**Comment by Castaglia** [comment]
Indeed, an 530 response for such cases would be better.  I'll work on making this happen.

**Comment by Castaglia** [comment]
This should now be fixed in `master`.  Thanks!
