### ISSUE TITLE
ProxyForwardTo and matches

### ISSUE THREAD

**Issue by jackmoot** [Castaglia/proftpd-mod_proxy#179]
In the documentation it says to use 

    ProxyForwardTo ^ftp\.example\.com [NC]

However this allows ftp.example.com.somedomain.com , so it would still allow to connect to any IP if you know the allowed string

I tried to use ^ftp\.example\.com$ but it doesn't seem to be supported

**Comment by Castaglia** [comment]
Can you provide your `proftpd -V` output?  I ask because the use of PCRE support (or not) may be relevant here; I would like to ensure that my local reproduction recipe matches the features you are using.

**Comment by jackmoot** [comment]
It's compiled with pcre but it's actually my fault for not looking carefully at logs, here is the output:

My config:

```
ProxyForwardTo ^server[0-9]+$ [NC]
```

log:

```
2020-10-27 14:46:14,169 mod_proxy/0.7[16151]: host/port 'server3:21' did not match ProxyForwardTo ^server[0-9]+$, rejecting
```

So the port has to be included in the match

I changed it to

```
ProxyForwardTo ^server[0-9]+\:21$ [NC]
```

Though maybe the documentation should be changed, as ^ftp\.example\.com still allows ^ftp\.example\.com.* (all domains)

**Comment by Castaglia** [comment]
I've tried to improve the docs, examples for this.  Thanks!
