### ISSUE TITLE
error reading ProxyReverseServers file '/opt/users/user.json': Operation not permitted

### ISSUE THREAD

**Issue by Bboy4life** [Castaglia/proftpd-mod_proxy#184]
After I run a chmod to increase permisions of the folder /opt/users/, I started getting this error:

      error reading ProxyReverseServers file '/opt/users/user.json': Operation not permitted

It always worked. Just the chmod, and eveything went to hell. I tried everything, even running the service as root. Nothing worked.

Just copy the json to another folder, and change the ProxyReverseServers  to that folder ;)

**Comment by Castaglia** [comment]
What specifically were the permissions changes you applied to your `/opt/users/` directory (and why)?

**Comment by Bboy4life** [comment]
The permissions were 644

After 666, because I needed to access to the files via ssh

Then I tried to return to 644 again, but error was still there

**Comment by Castaglia** [comment]
World-writable `ProxyReverseServers` files are not allowed/trusted by mod_proxy, because it means that any user on the system can write/modify those files.  There should be debug-level log message (not in the `ProxyLog`, but in general ProFTPD logging) about this, something like:
```
    pr_log_debug(DEBUG0, MOD_PROXY_VERSION
      ": unable to use world-writable ProxyReverseServers '%s' "
      "(perms %04o): %s", orig_path, st.st_mode & ~S_IFMT, strerror(xerrno));
```

**Comment by Bboy4life** [comment]
> World-writable `ProxyReverseServers` files are not allowed/trusted by mod_proxy, because it means that any user on the system can write/modify those files. There should be debug-level log message (not in the `ProxyLog`, but in general ProFTPD logging) about this, something like:
> 
> ```
>     pr_log_debug(DEBUG0, MOD_PROXY_VERSION
>       ": unable to use world-writable ProxyReverseServers '%s' "
>       "(perms %04o): %s", orig_path, st.st_mode & ~S_IFMT, strerror(xerrno));
> ```
> 
> This same check, for world-writable permissions, applies to the _directory_ containing these files as well -- `/opt/users/` in your case. Because even if the _file_ is not world-writable, being in a world-writable directory means that any user on the system can _delete_ that file, and write a new one.

**Comment by Bboy4life** [comment]
Yes, it's logical. A entry log would have been really helpful

**Comment by Castaglia** [comment]
I've added more logging to the `ProxyLog` for this in master, and added the above discussion to the `ProxyReverseServers` documentation.
