### ISSUE TITLE
mod_proxy leaks memory per data transfer

### ISSUE THREAD

**Issue by jw-hn** [Castaglia/proftpd-mod_proxy#189]
We recently noticed some of our proxies showing extreme memory spikes that we could not place, as the traffic didn't seem out of the ordinary. Memory usage of proftpd would grow as high as 1,5 - 2gb which seems excessive for a proxy. Our own investigation has led us to believe this happens when specific clients try to connect through the proxy, but only during some specific actions. An example we have found is the ELFinder: https://github.com/Studio-42/elFinder

After looking through our logfiles we have found a scenario with which we can consistently reproduce the issue:
- Make a 100-folder deep nested structure of folders
- Place an empty file in the deepest folder
- Upload the whole shebang through ELFinder
- Memory usage of the proftpd process (heap) starts growing excessively

Since it's very well possible more clients behave like this, we hope
to find a way to restrict this on the proxy side of things.

We hope you can help us debug this issue, or steer us in the right

direction if it is a matter of configuration. To make things easier
I've attached the following logs:
- Backend xferlog
- Proxy extendedlog
- Proxy proxylog
- Proxy trace log
- Proxy xferlog

I've also attached an example of our proxy/proftpd config.

We first noticed the issue at proftpd version 1.3.6 with mod_proxy 0.4.
We tried updating to proftpd 1.3.7, with mod_proxy 0.7 which sadly does not fix this issue.

[logs.zip](https://github.com/Castaglia/proftpd-mod_proxy/files/5874647/logs.zip)

**Comment by Castaglia** [comment]
Do you use `.ftpaccess` files at all?  If not, does this memory usage behavior change if you use _e.g._:
```
AllowOverride off`
```
The [`AllowOverride`](http://www.proftpd.org/docs/modules/mod_core.html#AllowOverride) directive -- enabled by default -- tells ProFTPD to scan every directory for a `.ftpaccess` file.  I am wondering if that behavior is somehow contributing to this memory usage.

**Comment by jw-hn** [comment]
Thanks for the reply, we do not use .ftpaccess files. Just tried disabling the AllowOverride (on the proxy, then on both the proxy and the back-end just to be sure), no dice. Usage still easily grows to ~400MB.

**Comment by pvdputte** [comment]
We are also coping with huge memory consumption of a proxying proftpd at times (mod_proxy 0.5).

We can e.g. reproduce it with filezilla as client, downloading a directory containing many files and folders, deeply nested.
E.g. thousands of files and folders with paths like

/some/root/folder/username/som-directory/another_long.directory.name/tmp/update-extraction-4f225817/webform/modules/webform_bootstrap/tests/modules/webform_bootstrap_test_module/webform_bootstrap_test_module.libraries.yml

We have a core dump file of such a 1.4 GiB process and after examination with od it seems to contain 99% null characters.
During the transfers it grows about one megabyte per second. When the client disconnects the process exits, returning the memory.

**Comment by Castaglia** [comment]
@pvdputte OK, that's good to know.  It sounds like something is leaking memory during the directory listing; for ProFTPD, that usually means something is allocating a memory pool in some loop, and those pools aren't released until the transfer ends.  It's _possible_ that newer versions of `mod_proxy` have addressed this, so it's always worth trying the latest version of the module, to see if the issue still occurs.

I'll see if I can reproduce this behavior locally.

**Comment by Castaglia** [comment]
I've reproduced this behavior locally, and have identified the contributing factors.  I'll be posting a PR for this shortly.

**Comment by Castaglia** [comment]
@jw-hn @pvdputte I believe that https://github.com/Castaglia/proftpd-mod_proxy/issues/189 should fix this issue.  Care to try it out, verify that in your environments?

The causes I found indicated that the memory leak is not client-specific; no matter what kind of data transfers occurred (uploads, downloads, directory listings), and no matter what client was used, over time, this memory spike/bloat would occur.  I suspect this behavior was seen for your clients because they created many separate transfers, as they walked the filesystem doing a mirroring sort of behavior.

**Comment by Jayfrown** [comment]
@Castaglia I can confirm that the case described in the OP (ie. uploading a nested folder structure 100 folders deep through ELFinder) now shows steady memory usage in an environment where we saw proftpd invoke the OOM killer before applying this branch, under the same conditions.

That is to say - nice work! Will you be able to include this in a release any time soon?

**Comment by Castaglia** [comment]
@Jayfrown thanks.  Yes, I am thinking to do another `mod_proxy` release soon, hopefully this coming weekend.

**Comment by pvdputte** [comment]
Hi,

Previous version: process size +/- 330 MiB after 3 minutes of transferring a deeply nested tree of small files, and increasing fast.
This version: process size +/- 100 MiB after 3 minutes, but does not keep increasing as fast anymore as at the start.

So it's definitely a huge improvement! Thanks.

It still keeps growing though... But as far as I can see, after the first 100MiB RSS is consumed it keeps going up but at a much slower pace. For our use case, this is perfectly acceptable.

**Comment by Castaglia** [comment]
@Jayfrown FYI, I've just released [v0.8](https://github.com/Castaglia/proftpd-mod_proxy/releases/tag/v0.8), which contains this bugfix.
