### ISSUE TITLE
Different problems in forward proxy mode

### ISSUE THREAD

**Issue by MichaelHof** [Castaglia/proftpd-mod_proxy#196]
Hi,

we run a moderate loaded forward proxy with this configuration:

> ProxyEngine On
>ProxyTables /tmp
>ProxyRole forward
>ProxyTLSEngine auto
>ProxyTLSVerifyServer off
> <Class forward-proxy>
>    From 0.0.0.0/0
>    ProxyForwardEnabled on
>  </Class>
>ProxyForwardMethod user@host

it is handled through xinetd:
>service ftp
>{
  >      flags           = IPv4
  >      disable         = no
 >      socket_type     = stream
>       protocol        = tcp
>        wait            = no
>        user            = root
>        instances       = UNLIMITED
>        server          = /usr/local/sbin/in.proftpd
 >       server_args     = -c /etc/proftpd.conf -S 0.0.0.0
>}

We sometimes gets this error which does not seem to affect the client at all:

> proftpd[8399]: 0.0.0.0 - mod_proxy/0.8: failed to initialize SQLite datastore: No such file or directory
> proftpd[8399]: 0.0.0.0 - mod_proxy/0.8: unable to initialize reverse proxy, failing to start up: No such file or directory

in trace.log we can see this:
>2021-04-21 09:50:31,419 [13920] <proxy.db:1>: (sqlite3): schema 'proxy_tls': [error 17] statement aborts at 14: [SELECT session FROM proxy_tls_sessions WHERE vhost_id = ? AND backend_uri = ?;] database schema has changed
>2021-04-21 09:50:31,422 [13919] <proxy.db:1>: (sqlite3): schema 'proxy_tls': [error 17] statement aborts at 14: [SELECT session FROM proxy_tls_sessions WHERE vhost_id = ? AND backend_uri = ?;] database schema has changed
>2021-04-21 09:50:31,444 [13922] <proxy.db:1>: (sqlite3): schema 'proxy_tls': [error 5] database is locked in "PRAGMA journal_mode = MEMORY;"
>2021-04-21 09:50:31,444 [13922] <proxy.db:3>: attempt #1, database busy, trying 'PRAGMA journal_mode = MEMORY;' again

But from time to time we get this error and mod_proxy suddenly stops to work at all and we need to delete the sqlite databases and restart proftpd:
> proftpd[12112]: 0.0.0.0 - mod_proxy/0.8: error opening database '/tmp/proxy-reverse.db' for schema 'proxy_reverse', version 6: Invalid argument

Any idea how we can solve this?

Kind Regards
Michael

**Comment by MichaelHof** [comment]
A little update, i switched away from xinetd and started proftpd standalone and it looks like this solved the problem.

**Comment by Castaglia** [comment]
Interesting.  I'm glad you were able to find a workaround, but this _does_ point out an area for improvement with `mod_proxy`.  I admit that I do all my development with `ServerType standalone`, and _rarely_ do I try `ServerType inetd`.  So I may re-open/repurpose this ticket, to see what improvements I can made, for other users who may run into this gotcha.

Thanks for the report!

**Comment by MichaelHof** [comment]
Thanks for your reply. It is running without problems since i switched to standalone, so indeed it looks like this was caused by the xinetd mode. Let me know if I can support you with any information.

**Comment by Castaglia** [comment]
I've filed #199 for tracking improvements on along these lines.  Thanks!
