### ISSUE TITLE
Support FTP directory listing parsing/translation

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_proxy#21]
Some FTP servers support the newer MLSD command; older FTP servers do not, and only support the LIST command (with varying formats).  Some FTP clients thus want to use the MLSD command, against older servers which only support LIST.  The mod_proxy module could handle the parsing of the LIST format, and reformat it as an MLSD response for the frontend client.

**Comment by sc911** [comment]
That would be great! Just ran into this while trying to reverse proxy vsftp, trying to access it with FileZilla. Solution by now: using WinSCP...

**Comment by Castaglia** [comment]
You might be able to work around this by using:
```
<IfModule mod_proxy.c>
  ...
  # Tell mod_proxy to show the backend server responses to the FEAT command
  ProxyOptions ShowFeatures
  ...
</IfModule>
```
See the [`ProxyOptions`](https://htmlpreview.github.io/?https://github.com/Castaglia/proftpd-mod_proxy/blob/master/mod_proxy.html#ProxyOptions) docs for the `ShowFeatures` option.

**Comment by Castaglia** [comment]
Ah, interesting; I would have thought that FileZilla would be a nice client, and fall back to `LIST` if `MLSD` is not available.  Huh.  Thanks for that info; that helps show the need for this feature.

**Comment by Castaglia** [comment]
One possible implementation for this would be to incorporate DJB's [ftpparse](https://cr.yp.to/ftpparse.html) library into `mod_proxy`...

**Comment by Castaglia** [comment]
There's some consideration needed for the command mapping we want to support.  I think the following is doable, as this is the driving use case:
* `MLSD` (frontend) <-> `LIST` (backend)
* `MLST` (frontend) <-> `NLST` (backend)

What about, though:
* `LIST` (frontend) <-> `MLSD` (backend)
* `NLST` (frontend) <-> `MLST` (backend)

Are these as needed/desired?

**Comment by Castaglia** [comment]
Note that having https://github.com/proftpd/proftpd/pull/173 implemented in ProFTPD would help with the development/testing of this `mod_proxy` feature.

**Comment by Castaglia** [comment]
@sc911 I think that, with https://github.com/Castaglia/proftpd-mod_proxy/pull/171, this should now be possible.  In your mod_proxy config, you would use:
```
ProxyDirectoryListPolicy LIST
```
With this, any `MLSD` commands from FileZilla would be turned into `LIST` commands to _e.g._ vsftpd, by `mod_proxy`.  And the `LIST` response would be translated, by mod_proxy, into the `MLSD` response format for FileZilla.

**Comment by Castaglia** [comment]
For the next related feature (for a separate ticket), perhaps mod_proxy should auto-detect the lack of support for the `MLSD` command on the backend server, and automatically set the "LIST" directory list policy?
