### ISSUE TITLE
Failing to set reverse proxy in a VirtualHost block

### ISSUE THREAD

**Issue by hilsonp** [Castaglia/proftpd-mod_proxy#222]
Hello,

Thank you so much for this great project !

One old java client only able to speak FTPS+TLSv1.0, I must connect to one server target_server:5678 that requires FTPS+TLSv1.2.
The connection uses a login, a password and a CRT (no need for a private key).
The goal is to keep the login and password known at the app level. If possible, I would like to keep the CRT at the app level too (as there is no need of private key).

I could compile and setup proftpd+mod_proxy as an ftps proxy between the app and the FTPS server for ONE login like this:
```
ServerName      "ProFTPD configured as proxy"
ServerType      standalone
DefaultServer     on

PidFile /var/run/proftpd.pid

DefaultAddress 127.0.0.1
SocketBindTight on

TransferLog /var/log/proftpd/xferlog.log
SystemLog /var/log/proftpd/proftpd.log

UseIPv6       off
Umask       022
MaxInstances      30
User        proftpd
Group       proftpd
AllowOverwrite    on

<Limit SITE_CHMOD>
  DenyAll
</Limit>

TLSEngine on
<IfModule mod_tls.c>
  ## Configuration on the server:
  # cd /home/sites/proftpd/conf
  # openssl genrsa -out proftp.key 1024
  # openssl req -new -x509 -days 3650 -key proftp.key -out proftp.crt
  # chown sonic:proftpd *
  # chmod 660 *

  TLSRSACertificateFile /home/sites/proftpd/conf/proftp.crt
  TLSRSACertificateKeyFile /home/sites/proftpd/conf/proftp.key
  TLSLog /var/log/proftpd/proxy.log
  TLSOptions EnableDiags NoSessionReuseRequired
  TLSProtocol TLSv1
  TLSRequired off
  TLSVerifyClient off
  #TLSRenegotiate none
</IfModule>

<IfModule mod_proxy.c>
  ProxyTables /dev/shm/proftpd_mod_proxy
  ProxyLog /var/log/proftpd/proxy.log
  TraceLog /var/log/proftpd/proxy.log
  ProxyTLSOptions EnableDiags
  Trace \
    proxy:30 \
    proxy.conn:30 \
    proxy.ftp.conn:30 \
    proxy.ftp.ctrl:30 \
    proxy.ftp.data:30 \
    proxy.ftp.msg:30 \
    proxy.ftp.sess:30 \
    proxy.ftp.xfer:30 \
    proxy.inet:30 \
    proxy.netio:30 \
    proxy.reverse:30 \
    proxy.session:30 \
    proxy.tls:30 \
    proxy.uri:30 \
    tls:30
</IfModule>

  ProxyEngine On
  Port 5678
  CreateHome on
  RequireValidShell               off
  ProxyRole reverse
  #ProxyOptions UseReverseProxyAuth
  ProxyTLSEngine on
  ProxyTLSVerifyServer off
  ProxyTLSProtocol TLSv1.2
  ProxyReverseServers ftps://target_server:5678
  ProxyTLSCertificateFile /home/sites/proftpd/conf/first_user.pem
```

If I put the last paragraph in a VirtualHost block, it to connect  to the target SFTP server.
_Edit: I mean FTPS server, not FTPS server_

I see a line `<proxy:15>: found group 'NONE' for command 'AUTH'`
This has probably nothing to do but we are maybe in a case like https://github.com/Castaglia/proftpd-mod_proxy/issues/59

Here is the block:
```
<VirtualHost 127.0.0.1>
  ProxyEngine On
  Port 5678
  CreateHome on
  RequireValidShell               off
  ProxyRole reverse
  #ProxyOptions UseReverseProxyAuth
  ProxyTLSEngine on
  ProxyTLSVerifyServer off
  ProxyTLSProtocol TLSv1.2
  ProxyReverseServers ftps://target_server:5678
  ProxyTLSCertificateFile /home/sites/proftpd/conf/first_user.pem
</VirtualHost>
```

What am I missing here ?

Thank you.

My "proftpd -V" gives this:
```
Compile-time Settings:
  Version: 1.3.7d (maint)
  Platform: LINUX [Linux 3.10.0-327.36.1.el7.x86_64 x86_64]
  Built: Mon Jun 13 2022 12:40:19 CEST
  Built With:
    configure  '--with-includes=/usr/include/openssl:/usr/include:/usr/local/src/proftpd-1.3.7d/contrib:/usr/local/src/proftpd-1.3.7d/contrib/mod_proxy/include' '--with-libraries=/usr/lib:/usr/lib/ssl:/usr/lib/x86_64-redhat-linux6E/:/usr/local/src/proftpd-1.3.7d/contrib/mod_proxy/lib:/usr/lib64/openssl' '--enable-openssl' '--with-modules=mod_sql:mod_sql_sqlite:mod_tls:mod_sftp:mod_proxy' '--enable-dso'

  CFLAGS: -g2 -O2 -Wall -fno-omit-frame-pointer -fno-strict-aliasing
  LDFLAGS: -L$(top_srcdir)/lib -L$(top_builddir)/lib  -rdynamic -L/usr/lib64/openssl -L/usr/local/src/proftpd-1.3.7d/contrib/mod_proxy/lib -L/usr/lib/x86_64-redhat-linux6E/ -L/usr/lib/ssl -L/usr/lib
  LIBS:  -lssl -lcrypto -lssl  -lsqlite3  -lcrypto -lsupp -lcrypt -ldl

  Files:
    Configuration File:
      /usr/local/etc/proftpd.conf
    Pid File:
      /usr/local/var/proftpd.pid
    Scoreboard File:
      /usr/local/var/proftpd.scoreboard
    Header Directory:
      /usr/local/include/proftpd
    Shared Module Directory:
      /usr/local/libexec

  Info:
    + Max supported UID: 4294967295
    + Max supported GID: 4294967295

  Features:
    - Autoshadow support
    - Controls support
    - curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    - Memcache support
    - ncurses support
    - NLS support
    + OpenSSL support (OpenSSL 1.0.2k  26 Jan 2017, FIPS enabled)
    - PCRE support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    - Sodium support
    + Trace support
    + xattr support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_ENV_MAX = 2048
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_LOGIN_MAX = 256
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_PATH_MAX = 4096
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 10
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10
```

mod_proxy source code is from last week.

**Comment by Castaglia** [comment]
I'd like to make sure I understand your use case here.  You have an old FTPS client, and so the frontend FTPS proxy needs to support TLSv1.0 -- but then it should connect to a backend FTPS server that uses TLSv1.2.  The existing username/password used by your client should be authenticated by the backend server, correct?  Additionally, there is a client certificate that you'd also like to support.

I know it's confusing, but "SFTP" refers to an SSH-based file transfer protocol that isn't related to FTP at all.  So when you say "SFTP", you mean FTP over TLS (FTPS), correct?

Last, what are the error messages/logs you're seeing, when you try to start ProFTPD with your configuration?

**Comment by hilsonp** [comment]
You got it right. I spoke about SFTP by mistake. I ment FTPS.

The target_server is being renewed to a server that accepts only FTPS with TLSv1.2.

Actually, the client app connects to the old FTPS target_server using 2 different sets of login, a password and certificate.
Let's call them:

- first_user first_password and first_user.pem
- second_user second_password and second_user.pem

The client app supports FTP or FTPS with TLSv1.0 and cannot be modified except the FTPS server IP and port used for each user.

As you said, our client should be authenticated by the backend server using the login, password and certificate set in the client app.
During my tests, I found out that I only needed to set `ProxyTLSCertificateFile /home/sites/proftpd/conf/first_user.pem` without needing to embed the private key in the pem file nor specifying a `ProxyTLSCertificateKeyFile`.

I would like to:

- Keep the login/password configured at the app level and authentication made only by the backend server. The proxy should not need to know the login/password (no linux user to be created, ...).
- Keep the CRT at the app level (as there is no need of private key). But if that is not possible, I can live with that BUT this forces me to have VirtualHost listening on different ports (one port per user) so that I can configure one pem file per VirtualHost

I do NOT get any error message when starting proftpd with the VirtualHost configuration.
I see that mod_proxy is triggered and starts negociation with the backend FTPS server but it does something different and the connection fails.

Do you need a full log with and without the VirtualHost ? I'll need to offuscate quite a few things ;-)
Maybe the best is to tell me exactly the log settings you need.

Thank you very much for you fast reaction. This is much appreciated.

**Comment by Castaglia** [comment]
To help see what's happening, I'd like to get the following logs:
* [Debug logging](http://www.proftpd.org/docs/howto/Debugging.html), using debug level 10
* `ProxyLog`
* `TLSLog`

And then, based on what we find in those logs, I may request some additional trace logging.

**Comment by hilsonp** [comment]
[proftpd.zip](https://github.com/Castaglia/proftpd-mod_proxy/files/9014725/proftpd.zip)
Here attached is a zip with for both tests (one with virtual host defined, one without):

- The proftpd.conf file
- The proftpd stdout+stderr captured using debug level 10
- The logfile with ProxyLog+TLSLog + TraceLog
- The java client error message if any

Sorry for the time it took to upload those but I was out of the office and needed to offuscate a few things from my customer first.

Thank you.

**Comment by Castaglia** [comment]
Great, thanks.  Based on the provided configurations, I think I see what's happening here.  One of the key things to know, about the ProFTPD configuration file format, is that directives outside of any `<VirtualHost>` or `<Global>` sections _are not globally applied_.  (There are a few exceptions, but they are exceptions, not the norm.)  I try to cover this in the [virtual server howto](http://www.proftpd.org/docs/howto/Vhost.html), but it's a detail that can be easily missed.

Let's first look at your working config file, the one _without_ any `<VirtualHost>` section.  You configure your TLS certs/keys for `mod_tls` and for `mod_proxy`.  All of these directives are outside of `<VirtualHost>` and `<Global>` sections, so they apply only to the default vhost -- and that's the one that you configure with a `DefaultAddress` and `Port`.  So when your Java client connects, `mod_tls` is enabled (so the frontend FTPS handshake/connection works), _and_ `mod_proxy` is enabled (so the backend FTPS handshake/connection works).

For the configuration that _does_ use `<VirtualHost>`, we see that the `mod_proxy` directives are inside of that `<VirtualHost>` section (which is good) -- but the `mod_tls` directives are not.  And that is why, when the Java client connects using this configuration, it tries to send the FTP `AUTH` command to start the TLS handshake, and it fails (since `mod_tls` is not enabled).

A "quick fix" would be to modify your `<VirtualHost>` config file slightly, and enclose the `mod_tls` configuration in a `<Global>` section, like so:
```
<IfModule mod_tls.c>
  # Apply the same TLS settings for all vhosts
  <Global>
    TLSEngine on
    ...
  </Global>
</IfModule>
```

Now, if you want to have _different_ TLS settings (such as `TLSProtocol`) for your different vhosts (_i.e._ the vhost listening on the default port 21, and your custom/explicit vhost listening on port 6808), you can have the same `mod_tls` directives, with different values, inside of your `<VirtualHost>` section.

Does this make sense?

**Comment by hilsonp** [comment]
Thank you very much !
This solved my problem and my configuration is fully functional now. 
Keep up the good work and incredible support!

**Comment by Castaglia** [comment]
Excellent, I'm glad to hear it's working now as you need.  Cheers!
