### ISSUE TITLE
Stuck connection after FTP command "NLST /not-exists" with TLS data connection enabled

### ISSUE THREAD

**Issue by vizustom** [Castaglia/proftpd-mod_proxy#244]
I found a serious bug in proxy operation in a situation where the proxy communicates with the backend server over TLS (ctrl+data) and the FTP client sends a proxy NLST command to a non-existent directory. The backend responds correctly with an error 550, but the proxy no longer passes the error to the client and stops communicating with the client. If the TLS encryption of the data connection between the proxy and the backend server is disabled, the error from NLST will be returned to the client as normal.

With the "ProxyTLSTransferProtectionPolicy required" setting, the FTP command "NLST /not-exists" does not return an error to the FTP client. With the "ProxyTLSTransferProtectionPolicy clear" setting, the proxy returns the error correctly.

We found a bug when verifying a broken WordPress update via FTP. WP tries directories one by one and often queries non-existent directories with the NLST command. We created a test PHP script that demonstrates the bug.

## Error in proxy.log
    2023-02-24 11:28:08,014 mod_proxy/0.9.2[1198528]: TLS negotiation timed out (30 seconds)
    2023-02-24 11:28:08,014 mod_proxy/0.9.2[1198528]: panic: SSL_ERROR_SSL, line 370: 
       (1) error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
    2023-02-24 11:28:08,014 mod_proxy/0.9.2[1198528]: unexpected OpenSSL error, disconnecting

## Attachments
I am attaching the configuration and logs. The IP addresses were changed as follows:
- client 1.2.3.4
- proxy server 2.3.4.5
- backend server 3.4.5.6

Logs ok-*.log contain communication when setting "ProxyTLSTransferProtectionPolicy clear" and error-*.log when setting "ProxyTLSTransferProtectionPolicy required"

[conf-log-test.zip](https://github.com/Castaglia/proftpd-mod_proxy/files/10825015/conf-log-test.zip)

## Environment
- CentOS 8 Stream, x64
- ProFTPD 1.3.8, mod_proxy 0.9, mod_vroot 0.9.11, see compilation.sh, compliled 6 February 23 from master
- OpenSSL 1.1.1k
- FTP backend server PupeFTPD 1.0.49
- FTP clients on Windows 10: PHP 8.1.16 Win64 NTS, Total Commander 10.50 x64
- FTP clients on CentOS 8: PHP 8.1.13 x64, PHP 7.4.30 x64

## Workarround
Set "ProxyTLSTransferProtectionPolicy clear" in proftpd.conf

**Comment by Castaglia** [comment]
Thanks!  That is indeed a nasty bug.  I've just created https://github.com/Castaglia/proftpd-mod_proxy/pull/245 which should handle this.  It passes my (added) regression tests.  Would you be able to try it out in your environment, see if it correct the issue for you as well?

**Comment by vizustom** [comment]
I recompiled ProFTPd with mod_proxy branch c72e0da and now the FTP command "NLST /not-exists" correctly returns an error to the FTP client even with the default proxy setting ("ProxyTLSTransferProtectionPolicy required"). Good job! Thanks for the quick fix.

**Comment by Castaglia** [comment]
Now fixed in master.  Thanks!
