### ISSUE TITLE
Debian 12: "proftpd: symbol lookup error: /usr/lib/proftpd/mod_proxy.so: undefined symbol: OPENSSL_init_ssl"

### ISSUE THREAD

**Issue by AceSlash** [Castaglia/proftpd-mod_proxy#252]
Hello,

On Debian 12, after installing the "proftpd-mod-proxy" package and adding the line "LoadModule mod_proxy.c", proftpd doesn't start with the following error:
```
/usr/sbin/proftpd: symbol lookup error: /usr/lib/proftpd/mod_proxy.so: undefined symbol: OPENSSL_init_ssl
```
Looks like the Bookworm code didn't get the fix from #249 .

Is there a way around that or is my only choice to compile proftpd?

**Comment by Castaglia** [comment]
Unfortunately, we don't provide the packages, only the source code.  So it may be that you need to build from source, until the maintainer for that Debian package provides an updated/fixed version of that package.

**Comment by AceSlash** [comment]
I have indeed compiled from source and it's working fine.

Thank you for providing this mod, it is very useful :+1:
