### ISSUE TITLE
Limit proxy data transfer

### ISSUE THREAD

**Issue by shunshunbu** [Castaglia/proftpd-mod_proxy#259]
How to use a reverse proxy to get the size of the file on the proxy server, write the file to the specified path of the proxy file, and do a security check to determine whether the conditions are met and sent to the back-end server through the proxy

**Comment by Castaglia** [comment]
This does not sound like a use case for which `mod_proxy` is designed.  It is meant only to proxy sessions to the backend server; the proxy itself (and its filesystem) is not involved in the session in any way.

**Comment by shunshunbu** [comment]
> This does not sound like a use case for which `mod_proxy` is designed. It is meant only to proxy sessions to the backend server; the proxy itself (and its filesystem) is not involved in the session in any way.

OK，thank you so much
