### ISSUE TITLE
Limit proxy DenyUser

### ISSUE THREAD

**Issue by shunshunbu** [Castaglia/proftpd-mod_proxy#261]
when i use <Limit> DenyUser bob </Limit> in reverse proxy,its dose not work, the user bob still able to connect the ftp server,
Is there a problem somewhere？thank u

**Comment by shunshunbu** [comment]
> when i use DenyUser bob in reverse proxy,its dose not work, the user bob still able to connect the ftp server, Is there a problem somewhere？thank u

like this <Limit LOGLIN>DenyUser bob </Limit>

**Comment by Castaglia** [comment]
In most proxy cases, the client is not authenticating _to the proxy_, it is authenticating to the backend server.  The proxy, in this case, doesn't inspect the session, so it is not going to impose any restrictions.

Your backend server configuration would need to have that:
```
<Limit LOGIN>
  DenyUser bob
</Limit>
```

**Comment by shunshunbu** [comment]
> In most proxy cases, the client is not authenticating _to the proxy_, it is authenticating to the backend server. The proxy, in this case, doesn't inspect the session, so it is not going to impose any restrictions.
> 
> Your backend server configuration would need to have that:
> 
> ```
> <Limit LOGIN>
>   DenyUser bob
> </Limit>
> ```

Thank you, I'll try another method
