### ISSUE TITLE
Better handling of SQLite database contention

### ISSUE THREAD

**Issue by shunshunbu** [Castaglia/proftpd-mod_proxy#263]
When I tested concurrent connections using JMeter, I configured it to have 100 concurrent connections per second, all of which were for the same user and sent the same file, and then the proxy reported this error：
![proxy(1)](https://github.com/Castaglia/proftpd-mod_proxy/assets/150652140/44eff5b0-4110-4781-9125-fbdbfd9cfb5c)

May I ask how I can solve this problem？

**Comment by shunshunbu** [comment]
some proxy conf is:
 ```shell
ProxyRole  reverse
ProxyReverseConnectPolicy RoundRobin
ProxyDataTransferPolicy client

**Comment by Castaglia** [comment]
The "database is locked" error comes from `mod_proxy`'s use of SQLite as the on-disk database used for tracking state information across multiple separate processes/sessions.  When there are many concurrent sessions, or many sessions opening and closing rapidly, there will be contention on that database.

I'll see what I can do about making `mod_proxy` handle such "busy database" conditions a little better.

**Comment by Castaglia** [comment]
This should be fixed, at least be better behaved, in the latest code.  Thanks!

**Comment by shunshunbu** [comment]
> This should be fixed, at least be better behaved, in the latest code. Thanks!

OK，thank you
