### ISSUE TITLE
Questions about proxy delay

### ISSUE THREAD

**Issue by shunshunbu** [Castaglia/proftpd-mod_proxy#265]
first condition ：When I use the ftp command line client with a command similar to the following: "open ip port" to connect to the proxy server, I find that there will be a 10-second delay. Then I use tcpdump to capture packets and find that after the proxy server receives the ftp client's connection request, , the proxy request will be sent to the target server after 10 seconds. May I ask where this delay comes from and whether it can be shortened?

second condition ：But when the ftp client is deployed on the proxy server, this delay disappears, which is very surprising.

![企业微信截图_17097914166610](https://github.com/Castaglia/proftpd-mod_proxy/assets/150652140/a657f9e0-10f4-49d2-8e51-4fb46db2f10e)

**Comment by shunshunbu** [comment]
the proftpd.conf like this:
```shell
<VirtualHost ip>
 Port 7000
 MaxClients  10
 MaLoginAttempts 1
<IfModule mod_proxy.c>
     ProxyEngine on
     ProxyLog   /var/log/proxy.log
     ProxyRole  reverse
     ProxyReverseConnectPolicy RoundRobin
     ProxyDateTransferPolicy client
     ProxyReverseServers ftp://ip1:port
  </IfModule>
</VirtualHost>

**Comment by shunshunbu** [comment]
Hey, are you there? I read the source code in contrib/mod_proxy/lib/proxy/conn,c and found that PR_NETIO_STRM_OTHER will take five seconds and then be interrupted by the system. What is the reason for this delay? Hope you can provide answers
@Castaglia 
![企业微信截图_17104041533514](https://github.com/Castaglia/proftpd-mod_proxy/assets/150652140/00cb382b-7937-4480-8a8c-9c35c0e452cb)

**Comment by Castaglia** [comment]
Were you able to find a solution/answer to this question?  I've been away for work of late, so haven't had much time to look into these issues.

**Comment by shunshunbu** [comment]
> Were you able to find a solution/answer to this question? I've been away for work of late, so haven't had much time to look into these issues.

Yes, I found a solution to this problem, thank you
