### ISSUE TITLE
mod_proxy with sqlite vs selinux

### ISSUE THREAD

**Issue by pzeidler-dlr** [Castaglia/proftpd-mod_proxy#266]
Something to add to the documentation:

if sestatus is enforcing you need to make sure proftpd may write to the ProxyTables path.

with e.g.:
```
ProxyTables /var/ftp/proxy
```
then:
```sh
semanage fcontext --add --type public_content_rw_t '/var/ftp/proxy(/.*)?'
setsebool -P ftpd_anon_write=1
```
will make it all better. There may be better selinux types to use, of course.

**Comment by pzeidler-dlr** [comment]
Another thing mod_proxy wants to do is open a network connection (or two, or three) to the proxied systems.
`setsebool -P nis_enabled=1`
will allow it to.

**Comment by Castaglia** [comment]
SELinux section added to the mod_proxy docs.  Thanks!
