### ISSUE TITLE
Problem with RETR from backend server in forward proxy role

### ISSUE THREAD

**Issue by ratM1n** [Castaglia/proftpd-mod_proxy#3]
Hi!

i have problem with mod_proxy. it works as it should with all other commands i have tested but GET.

my proftpd config: http://pastebin.com/FRqr9JE9

trace log - http://pastebin.com/4ZQBeitu

RETR will not get thru to mod_proxy but will end in local mod_xfer

system is Centos 7.1 x86_64, proftpd is vanilla 1.3.5 from proftpd site and mod_proxy is latest from github repo.

./configure  --libexecdir="/usr/libexec/proftpd" --localstatedir="/var/run/proftpd" --disable-strip --enable-ctrls --enable-dso --enable-openssl --enable-shadow --enable-pcre --with-libraries="/usr/lib64/mysql" --with-includes="/usr/include/mysql" --with-shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_wrap:mod_ctrls_admin:mod_load:mod_proxy:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_geoip:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_readme:mod_auth_pam:mod_tls

running as : ./proftpd -n -d 10 -c /etc/proftpd.conf

**Comment by Castaglia** [comment]
Ah, I see the issue.  I've been developing mod_proxy all locally, using multiple proftpd vhosts as the proxy/backend servers.  This has the downside of not detecting issues like this; the PRE_CMD handlers in the proxy vhost would of course see the same filesystem as the backend vhosts.

**Comment by Castaglia** [comment]
This PR should fix things:

  https://github.com/Castaglia/proftpd-mod_proxy/pull/4

Note that this change will require using the proftpd source code from the 'master' branch in GitHub; fixing this issue required adding a new API to the core code.

**Comment by ratM1n** [comment]
Thanks for fast response Castaglia, now it works.

Really nice module and features, exactly the solution i was looking for!

**Comment by Castaglia** [comment]
Excellent!  I've merged the PR.

I'm still working on the documentation, preparing for a first release of the module, but I'm glad it's working well for you!  If there's anything else that you think mod_proxy should provide, just let me know.
