### ISSUE TITLE
forwarding proxy and ProxyForwardEnabled

### ISSUE THREAD

**Issue by ratM1n** [Castaglia/proftpd-mod_proxy#41]
from my proftpd.conf :
        ProxyEngine on
        ProxyLog /var/log/proftpd/proxy.log
        ProxyTables /var/run/proftpd/proxy

        ProxyRole forward
        ProxyForwardMethod user@host
        ProxyForwardTo ^web2 [NC]
        ProxySourceAddress 10.1.1.40

        <Class forward-proxy>
                From 0.0.0.0/0
                # Allow clients from this class to use FTP forward proxying
                ProxyForwardEnabled on
        </Class>

from trace.log :
2015-10-16 13:10:30,720 [2416] <netacl:10>: checking addr '1.2.3.4' against IP mask rule '0.0.0.0/0'
2015-10-16 13:10:30,720 [2416] <netacl:10>: addr '1.2.3.4' matched IP mask rule '0.0.0.0/0'

and from proxy.log :
2015-10-16 13:10:30,743 mod_proxy/0.3[2416]: forward proxying not allowed from client address 1.2.3.4 in <Class forward-proxy> (see ProxyForwardEnabled)

if i change 0.0.0.0/0 rule so it will not match, then i get to proxy.log:
2015-10-16 14:45:01,293 mod_proxy/0.3[3033]: forward proxying not allowed from non-RFC1918 client address 1.2.3.4

**Comment by Castaglia** [comment]
Which version of proftpd are you running?  I'll see what I can do to reproduce this locally; thanks for reporting the issue!

**Comment by ratM1n** [comment]
Hi, proftpd and mod_proxy both are latest from github repo. system is Centos 7

**Comment by Castaglia** [comment]
Thanks!  I managed to get some free time to reproduce this issue today.  It was indeed a bug in `mod_proxy`, and should now be fixed; I just pushed changes.  Could you try it out, when you get a chance, confirm that it works for you?

**Comment by ratM1n** [comment]
Thanks for your help, works graet now. mod_proxy is really nice addition to proftpd!

**Comment by Castaglia** [comment]
Excellent!  Thanks for confirming the fix.
