### ISSUE TITLE
Support storing reverse proxy data in external datastore

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_proxy#43]
Currently `mod_proxy` uses an SQLite database for storing data for implementing different `ProxyReverseConnectPolicy` algorithms.

In a distributed environment, where there might be multiple different `mod_proxy` servers running, that information may need to be stored in an external datastore (_e.g._ memcached, Redis, etc), so that all proxies can see/make use of the collective information.

**Comment by Castaglia** [comment]
Note that implementing this assumes some sort of schema versioning, _a la_ Issue #44 .

**Comment by skirmis** [comment]
👍 for Redis

**Comment by Castaglia** [comment]
Now that the ProFTPD `master` branch supports Redis, I can start to work on support for this in `mod_proxy`.

**Comment by skirmis** [comment]
Hi Castaglia! Any progress on Redis implementation into mod_proxy? Because I'm getting database is locked sometimes on high FTP traffic:/

**Comment by Castaglia** [comment]
@skirmis this has now been merged to master; see the mod_proxy docs for the new `ProxyDatastore` directive.
