### ISSUE TITLE
DSR support

### ISSUE THREAD

**Issue by benrubson** [Castaglia/proftpd-mod_proxy#49]
Hello,

As introduced [here](https://github.com/proftpd/proftpd/issues/174), could it be possible to implement DSR (Direct Server Return) in mod_proxy please ?
This would save / optimize bandwidth during data transfer : each file transfer would be directly established between the target server and the FTP client, without going through the proxy-server, which without DSR acts as a bottleneck.

DSR may also simplify the internal working of mod_proxy (as once commands are sent to the target server, target server replies by itself).
Perhaps we will have to use `MasqueradeAddress <proxy-server-address>` on target servers so that replies are made with the proxy-server address (well, data transfer must not go through proxy-server, so should not be as simple as that).

Thank you very much for your support :+1: 

Ben

**Comment by Castaglia** [comment]
Just to be very clear about what "DSR" means: you like an FTP client to connect to _e.g._ `mod_proxy`, and be proxied to a backend server.  When the client requests a data transfer using active data transfers, it would be the _backend_ server, *not* `mod_proxy`, which connects to the FTP client's machine; likewist, when a passive data transfer is requested, the backend server's address/port are sent to the FTP client, not `mod_proxy`'s address/port. Is this correct?

Would your use case also require/expect the use of FTPS?  I ask because the `mod_tls` module in ProFTPD makes some assumptions about the relationship of the TLS session on the control connection, and the TLS session on the data connections; these assumptions might be broken in the DSR scenario/flow.

**Comment by benrubson** [comment]
Yes, this is correct, your explanation is clear and precise.

On drawback side, I'm not sure all FTP clients will be happy to connect to an address (the backend server's one) which is different from the one they initially asked to connect to (the frontend / mod_proxy's one). Tests will tell us.
Perhaps  stateful firewalls which may exist on client side would also require some tuning.
However I don't see how to implement DSR differently...

I also expect to use FTP over TLS yes, as passwords on clear FTP channels can be stolen too easily...
If it can help, all the servers (mod_proxy and backend servers) can use the same certificate. A wildcard one can smartly do the trick.

Thank you !

Ben

**Comment by Castaglia** [comment]
Merged to master; this feature is now available by using the following in your mod_proxy configuration:

    ProxyOptions UseDirectDataTransfers

**Comment by benrubson** [comment]
Thank you very much, really :+1:
I will give it a try and put it into production as soon as possible, I will let you know !

**Comment by Castaglia** [comment]
If your backend servers are running ProFTPD, then you *will* need to add the following to their `proftpd.conf`:

    AllowForeignAddress on

And, if you are using `mod_tls`, you will also need to use:

    TLSOptions NoSessionReuseRequired

Without these, your direct data transfer connections will probably fail.

**Comment by benrubson** [comment]
Thank you for your advices :+1: 
Of course my backend servers are running ProFTPD.
They already use `TLSOptions NoSessionReuseRequired` as I had some issues from some FTP clients without it (could this option really open a security breach ?).

Regarding `AllowForeignAddress`, sounds like it could imply some [security risks](http://www.proftpd.org/docs/directives/linked/config_ref_AllowForeignAddress.html), right ?

Perhaps I could disable active mode, allowing only passive mode ? Any reason to leave active mode enabled today ?

Well, when I read [this](http://cr.yp.to/ftp/security.html), sounds like passive mode has some drawbacks too... Perhaps using TLS solves all the mentioned issues in this link ? Or perhaps ProFTPD has some security mechanisms against these passive attacks ? Would `UseDirectDataTransfers` break them ?

Thank you very much !

Ben
