### ISSUE TITLE
mod_proxy with frontend TLS

### ISSUE THREAD

**Issue by noirey** [Castaglia/proftpd-mod_proxy#5]
Add TLS support on mod_proxy !

- Allow "TLSEngine on" (or similar) on prodftpd with mod_proxy.
- Allow mod_proxy to connect to TLS ftp servers. Idealy mod_proxy checks what is supported and use TLS if available.

Thanks.

**Comment by Castaglia** [comment]
I've split this into two separate issues: one for frontend TLS (which I'm just about to merge to the master branch), and one for backend TLS (see Issue #10).

**Comment by Castaglia** [comment]
Now merged to master.
