### ISSUE TITLE
Support reverse proxying of SFTP/SCP sessions

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_proxy#56]
Just as `mod_proxy` does for FTP sessions, it would be great if `mod_proxy` could also proxy (reverse **and** forward) SFTP/SCP connections, _e.g._ for `mod_sftp`.

*Update as of 2022-05-04*: Since there is no clear path to implementing _forward_ proxying of SSH connections, I'm going to restrict the scope of this ticket to just _reverse_ proxying of SSH connections.

**Comment by Castaglia** [comment]
Implementing this functionality, in `mod_proxy`, would be _much_ easier if I could reuse the code that `mod_sftp` uses, for formatting the SSH2 packets and encrypting/decrypting them properly.  Obviously I could simply _copy_ the `mod_sftp` code into `mod_proxy`, but that's bad practice, code-wise.  So working on this may require/depend on some changes to `mod_sftp`.

**Comment by aderumier** [comment]
Hi, do you have a roadmap for this feature ?

**Comment by Castaglia** [comment]
@aderumier I do not, as yet, have any particular timeline planned for this feature.  However, I suspect that it may require some changes in the `mod_sftp` module itself, and thus will _probably_ happen after `proftpd-1.3.6-stable` is released.

Do you have particular need for that functionality?  If so, I'd like to hear more (perhaps via email) about it!

**Comment by aderumier** [comment]
@Castaglia No special need, I would like to have a reverse proxy sftp, something like your current reverse ftp implementation.  (I'm looking to build a reverse proxy with both ftp/sftp support).

**Comment by kevy1234** [comment]
I'm trying to set up an sftp reverse proxy server in DMZ too which relays sftp requests to the internal proftpd server, any suggestion?

**Comment by Castaglia** [comment]
@kevy1234 _if_ your reverse proxy needs are simple, you _should_ be able to use a simple TCP proxy (_e.g._ `haproxy`) to proxy the TCP connection between DMZ and backend server.  SFTP is a single TCP session.  So if your proxy doesn't _need_ to know anything about users, or specific algorithms -- if it only needs to proxy the connection, then a TCP proxy should work.

**Comment by kevy1234** [comment]
@Castaglia Would there be any security concerns? What we would like to do is terminate user connections in DMZ.
Thanks for the comments.

**Comment by Castaglia** [comment]
@kevy1234 An excellent question, with several different components.

Terminating connections at the DMZ is a Good Thing.  And fortunately, for SFTP/SCP, it is _usually_ enough to terminate the TCP connection at the DMZ, and have some TCP proxy relay that connection to the actual SFTP/SCP server within the LAN.  With this sort of arrangement, you can do TCP connection-based load balancing.  The external SFTP/SCP client does not (and *cannot*) know the IP address of the internal server handling the connection.  (Unfortunately, because of the DMZ relay, this also means that the internal server cannot know the IP address of the remote client; there are ways of handling this, though.)

Where `mod_proxy` will (in the future) help with this situation is to be able to do load balancing based on things like the SSH key used, or the specific users, _etc_ -- balancing based on information that is only available if the proxy speaks SSH, rather than just TCP.  The `mod_proxy` module would also allow for things like authenticating the users in the DMZ, and then having the backend SFTP/SCP session use a _different_ username, so that user authentication is centralized/managed in the DMZ, "at the edge" as it were.  Some deployments like that sort of arrangement, some do not.

Does that help answer some of your questions/concerns?

**Comment by kevy1234** [comment]
@Castaglia Very well explained, thank you!
If this is the case, instead of using mod_proxy we should be able to use Haproxy Tcp mode in DMZ to proxy FTP/FTPS connections as well, am I correct?

**Comment by Castaglia** [comment]
Unfortunately, using `haproxy` for _FTP/FTPS_, as well as SFTP, does *not* work that well.

The difference is that SFTP/SFTP is based on SSH, and SSH uses *single TCP connection only*.  This means that `haproxy`, acting as a TCP proxy, will work.

FTP/FTPS, however, uses *multiple independent TCP connections*: one for the control connection (over which the commands/responses are sent), and other _ephemeral_ data connections, one for each data transfer.  These data connections, to make matters worse, use ports which are dynamically negotiated over the control connection (that's the purpose of FTP's `PORT`, `PASV`, `EPRT`, and `EPSV` commands).  This means that `haproxy` would have to proxy _multiple_ TCP connections -- and it won't know _which_ TCP connections to proxy to the same backend servers.

So, short answer is this: `mod_proxy` is needed for proxying FTP/FTPS sessions (and this is what it does now).  `mod_proxy` does not (yet) work for proxying SFTP/SCP sessions; you should be able to use _e.g._ `haproxy` for proxying SFTP/SCP sessions for now.

**Comment by kevy1234** [comment]
In you future release it would be great if you can make sftp to ftp proxy work , and vise versa.

**Comment by Castaglia** [comment]
@kevy1234 Agreed -- but that would be a slightly different task (for which I've opened Issue #86 ).

**Comment by kevy1234** [comment]
Any progress on this feature?

**Comment by Castaglia** [comment]
This is currently waiting on some work in `mod_sftp` proper; see https://github.com/proftpd/proftpd/issues/435.  That will reduce the work greatly, _i.e._ avoiding having to re-implement/copy a lot of code.

**Comment by Bboy4life** [comment]
Hello @Castaglia, making this work would be awesome, i'm currently strugling with reverse sftp/scp proxying...

I will try the tcp proxy, many thanks :)

**Comment by Castaglia** [comment]
For the folks watching this ticket, I've just merged the initial support for SSH proxying into the master branch; note that it requires the latest code in master for ProFTD as well.

Currently supported:
* Reverse proxy (`ProxyRole reverse`)
* Load-balanced (non-sticky) reverse connection policies

The following items/features still need to be added, probably as follow-on issues:
* Forward proxy (`ProxyRole forward`), although I'm not sure how this would look for SSH
* Sticky reverse connection policies (`PerUser`, `PerGroup`)
* UMAC digests
* Encrypt-Then-Mac digests
* AAD ciphers (such as `aes-gcm@openssh.com`)

I still need to write up some docs for this, particularly with regard to handling publickey/hostbased authentication in proxied connections; it is not as transparent as one would hope, due to the SSH protocol specification.  Please feel free to contact me directly, if you'd like to try this out, while I work on the documentation.

**Comment by Castaglia** [comment]
I've just now merged support for the "sticky" reverse connection policies (`PerUser`, `PerGroup`, `PerHost`) for SSH connections.

In terms of remaining work, I've decided that _forward_ proxying of SSH connections will have to wait, as there is no clear path/means for implementing that in a general/interoperable manner.  As for the other items, I've filed separate tickets:
* Encrypt-Then-Mac digests (see #216)
* AAD ciphers such as `aes-gcm@openssh.com` (see #217)

Before I close _this_ ticket, however, I will finish the necessary proxying documentation.  As before, please feel free to contact me directly, if you'd like to try this out, while I work on the documentation.

**Comment by Castaglia** [comment]
Now implemented in master; I hopefully do a release soon.
