### ISSUE TITLE
Configuration Option to allow proxy to servers with replies not compliant with RFC 959

### ISSUE THREAD

**Issue by ws0w** [Castaglia/proftpd-mod_proxy#66]
EDIT: fix the RFC number

I had been trying to use proftpd with mod_proxy to reverse proxy to a commercial ftp server, but the connection failed. I traced the problem to the fact that the commercial ftp server replies with continuation lines that are not fully RFC 959 compliant. Specifically, the continuation lines begin with the status code and '-' (e.g., "220-"). In my case, replacing the commercial ftp server is not an option in the short term. It would be helpful if mod_proxy allowed a configuration option to allow this kind of non-compliant reply.

I have provided a patch that implements this feature.

Also, I ran into a problem reverse proxying using anonymous login with a blank password. When the backend server is not proftpd, anonymous login with a blank password appears to succeed, but subsequent commands fail.  The attached patch files also include a configuration option for this situation.

[ctrl_patch.txt](https://github.com/Castaglia/proftpd-mod_proxy/files/269251/ctrl_patch.txt)
[mod_proxy_patch.txt](https://github.com/Castaglia/proftpd-mod_proxy/files/269250/mod_proxy_patch.txt)

**Comment by Castaglia** [comment]
Could you provide an excerpt/example of the non-compliant multi-line response, so that I could create a regression test for this for `mod_proxy`?

Also, for the reverse proxying situation, how exactly did the subsequent commands fail?  Do you have logs?

Having the full information (including logs) helps me to understand the context of the provided patches.   Thanks!

**Comment by ws0w** [comment]
I've attached a text file with a sample reply that mod_proxy rejects. The commercial software on the backend is called SecureTransport, if that's relevant.

As for the reverse proxy failing for anonymous ftp without a password, I'll probably need to to do some more testing with tracing.

For now, I can say that anonymous logion to the commercial ftp server responds with the following reply whether or not the password is blank:

230 Virtual user anonymous logged in.
200 PBSZ 0 successful
200 Protection set to Private

going throuhg mod_proxy, an anonymous login with blank password results in this repy to the ftp client:

250 SITE command successful.
200 PBSZ 0 successful
200 Protection set to Private

Then subsequent commands produces this reply to the client:

425 Please login with USER and PASS.

Let me know if that's not enough information.

[ftpbanner.txt](https://github.com/Castaglia/proftpd-mod_proxy/files/272922/ftpbanner.txt)

**Comment by Castaglia** [comment]
Thanks for the example banner.  Turns out that `mod_proxy` might (now) be handling these multi-line responses better; see [this commit](https://github.com/Castaglia/proftpd-mod_proxy/commit/53275c3903d4b34b628188a5992eba1fb6eb128e).

**Comment by ws0w** [comment]
I'll test to be sure, but hat looks like it should do it. I like it better than my patch -- I was trying to preserve the default strict behavior.

**Comment by ws0w** [comment]
The issue with mod_proxy parsing the backend banner is fixed.

**Comment by Castaglia** [comment]
@ws0w would you care to open a separate ticket for the anonymous login with blank password issue? Thanks!

**Comment by ws0w** [comment]
I'd be happy to.  I'll create a pull request right  after that. :)
--
Dan Campbell
