### ISSUE TITLE
Proxy any TCP OOB marker/abort sequence, as well as ABOR command

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_proxy#78]
When a frontend FTP client sends the TCP "out-of-band" (OOB) marker for signalling an interruption on the data connection, those bytes should be proxied by `mod_proxy` to the backend server.  Similarly for any `ABOR` command that the frontend client may send.

**Comment by grzsmp** [comment]
Hi!
If I understand the above, the related snipped code is from mod_proxy.c, function MODRET proxy_data(...):
```
...
frontend_ctrlfd = PR_NETIO_FD(proxy_sess->frontend_ctrl_conn->instrm);
FD_SET(frontend_ctrlfd, &rfds);
if (frontend_ctrlfd > maxfd) {
    maxfd = frontend_ctrlfd;
}
...
#if 0
    /* Any commands from the frontend client take priority */

    /* NOTE: This is temporarily disabled, until I can better handle an
     * ABOR command on the frontend control connection whilst in the middle
     * of a data transfer.
     */
    if (frontend_ctrlfd >= 0 &&
        FD_ISSET(frontend_ctrlfd, &rfds)) {
      proxy_process_cmd();
      pr_response_block(FALSE);
    }
#endif
...
```
In my experience proftpd will run in infinite loop, hoging 100% cpu until some of the timeout occur. I have problem with some buggy clients, so I have added a code which just exit the loop when frontend_ctrlfd became ready, end terminate the process. 
So my question is what should happen if frontend_ctrlfd will be in set of ready files descriptors?

**Comment by Castaglia** [comment]
@grzsmp when you say "proftpd will run in infinite loop", are you referring to seeing `mod_proxy`, in this section of code, running in a tight loop, not interruptible by signals?

**Comment by Castaglia** [comment]
Fixed in master.
