### ISSUE TITLE
Reverse proxy backend selection based on frontend FTPS client certificate

### ISSUE THREAD

**Issue by hacor** [Castaglia/proftpd-mod_proxy#80]
Hello,

I'm studying `mod_proxy` for the moment and it looks like a great module.
I had a look around the other issues and I couldn't find one that addresses my question :-)

Is it possible to:

```
Client --- (FTPS, `client1.key`) --> mod_proxy (selects backend based on client key) --- (FTP) --> backend1 (for `client1.key1`) or backend2 (for `client2.key`)
```

And make `mod_proxy` select the backend based on the client key file? I have many ftp backends and all clients have their personal key.  Or is `PerUser` the only option I have right now?

Thanks for your time!
Best regards,

Hacor

**Comment by Castaglia** [comment]
Currently, on the `PerUser` policy would meet your needs.  I _think_ I can make this work, _assuming_ you use `mod_sql` and a custom `SQLNamedQuery` for looking up the backend servers; I'll update this issue when I find out more.  Thanks!

**Comment by Castaglia** [comment]
Do you absolutely need the lookup based on the client _key_, or can it be done based on any of the client certificate attributes, such as those made available via environment variables using the `StdEnvVars` [`TLSOption`](http://www.proftpd.org/docs/contrib/mod_tls.html#TLSOptions)?

I was also contemplating adding a way to get the certificate _fingerprint_ available as an environment variable.  The downside to using the _fingerprint_ (as opposed to the _key_) is that the fingerprint is based on the certificate; and if the certificate expires/rotates, the fingerprint will change -- but the _key_ might not.  On the other hand, it's best to keep the _key_ itself private, and **not** used/exposed anywhere (even in a database).  Thus using something _other_ than the key might be a good idea.

**Comment by hacor** [comment]
I was thinking about using the `CommonName` field of the clientkey. 
The backend servers would be simple ftp servers, no ssl connection needed. So the key-file is the _key_ to open a connection to the correct backend.

**Comment by Castaglia** [comment]
Using the CN _should_ work, assuming that your client certificates have unique enough CN values.  I'll work on a PR for `mod_tls`, to add the CN as an environment variable alongside the other `StdEnvVars` variable, _e.g._ `TLS_CLIENT_CN` (and `TLS_SERVER_CN`, for symmetry).

Then, once that is supported, you should then be able to use something like this for the `mod_proxy` configuration:

    <IfModule mod_proxy.c>
      ProxyEngine on
      ProxyRole reverse
      ProxyReverseServers sql://get-user-servers
      ...
    </IfModule>

And then, for the `mod_sql` configuration for supplying that `SQLNamedQuery` name of "get-user-servers":

    <IfModule mod_sql.c>
      SQLBackend ...
      SQLNamedQuery get-user-servers SELECT "url FROM proxy_backends WHERE cn = '%{env:TLS_CLIENT_CN}'"
    </IfModule>

The above assumes a SQL schema along the lines of:

    CREATE TABLE proxy_backends (
      cn TEXT PRIMARY KEY,
      url TEXT
    );

Since `mod_proxy` already uses SQLite, if you are not already using `mod_sql` with some other database, you can use the `mod_sql_sqlite` module and create a different database table for storing the mappings of CNs to backend servers.

**Comment by Castaglia** [comment]
Ha!  It looks like `mod_tls` _does_ already provide the `TLS_CLIENT_CN` environment variable -- it's simply not listed in the `mod_tls` docs.  I'll have to fix that.  In the mean time, you might try the above configuration, and using the following for `mod_tls`:

    <IfModule mod_tls.c>
      ...
      TLSOptions StdEnvVars
    </IfModule>

**Comment by hacor** [comment]
Wow! Looks promising. I'll keep you posted on the results. For the moment I'm still struggling on getting ProFTPd build correctly from source, it keeps on throwing me errors during the linking process, but getting there! (I usually took the standard ubuntu distro package, so I never build it from source)

Thanks for the nice docs!

**Comment by Castaglia** [comment]
Were you ever able to make this work?

**Comment by hacor** [comment]
To be honest, I gave up on this client SSL certificate. 
I want my FTP service to be available for most clients, but installing a certificate in an FTP client isn't easy for just 'standard' FTP users.

Therefor I successfully use the proxy now with backend selection based on username and password.

**Comment by Castaglia** [comment]
Fair enough.  I've added the above example as a FAQ/use case to the docs; see https://github.com/Castaglia/proftpd-mod_proxy/commit/ef5765d2f4e0fb07f2a4288c9c65ded198eeae70.
