### ISSUE TITLE
Trouble building mod_proxy against debians proftpd-dfsg-1.3.5

### ISSUE THREAD

**Issue by andreasfenzsw** [Castaglia/proftpd-mod_proxy#83]
Hello,

i try to build mod_proxy against the proftpd-dfsg-1.3.5 source package. I know this is different from the upstream. The error: 

```
make[3]: Entering directory '/usr/src/proftpd-dfsg-1.3.5/contrib/mod_proxy'
/bin/bash ../../libtool --mode=compile --tag=CC gcc -D_FORTIFY_SOURCE=2 -DHAVE_CONFIG_H  -DLINUX  -I. -I./incltrong -Wformat -Werror=format-security -Wall -DPR_SHARED_MODULE -c mod_proxy.c -o mod_proxy.lo
libtool: compile:  gcc -D_FORTIFY_SOURCE=2 -DHAVE_CONFIG_H -DLINUX -I. -I./include -I../.. -I../../include -I/ecurity -Wall -DPR_SHARED_MODULE -c mod_proxy.c  -fPIC -DPIC -o .libs/mod_proxy.o
In file included from mod_proxy.c:29:0:
mod_proxy.h:31:23: fatal error: ccan-json.h: Datei oder Verzeichnis nicht gefunden
 #include "ccan-json.h"
```

Any hints? Should i use the original proftpd? Which version 1.3.5 or 1.3.6rc2?

Thanks
Andreas

**Comment by Castaglia** [comment]
`mod_proxy` currently depends on changes that are only in the proftpd [master branch](https://github.com/proftpd/proftpd) on GitHub; version 1.3.5 does not have the necessary API/headers support.  Using 1.3.6rc2 _might_ work; I've not tried it lately.

**Comment by gengshuhui** [comment]
1.3.6rc2 works.

**Comment by Castaglia** [comment]
Thanks for the confirmation @gengshuhui !  I've updated the HTML docs to hopefully make this clearer.
