### ISSUE TITLE
Proxied Anonymous Login fails with a blank password -- SecureTransport backend

### ISSUE THREAD

**Issue by ws0w** [Castaglia/proftpd-mod_proxy#84]
I ran into a problem with reverse proxy using anonymous login with a blank password. When the backend server is SecureTransport, anonymous login with a blank password appears to succeed, but subsequent commands fail.  

When the user just hits ENTER at the password prompt (blank password), internally mod_proxy sends a PASS command to the backend server with zero arguments instead of a PASS command with one argument that is an empty string. That's ok when the backend is another proftpd server.

This is what the users sees with blank password:
```
Name (servername:dan): anonymous
331 Password required for anonymous.
Password: 
250 SITE command successful.
200 PBSZ 0 successful
200 Protection set to Private
ftp> dir
425 Please login with USER and PASS.
ftp> 
```

This is what the use sees with non-blank password:
```
Name (servername:dan): anonymous
331 Password required for anonymous.
Password: 
230 Virtual user anonymous logged in.
200 PBSZ 0 successful
200 Protection set to Private
ftp> 
```

Notice that with the blank passowrd, the users sees:

`250 SITE command successful.`

instead of 

`230 Virtual user anonymous logged in.`

I fixed this problem in my environment by adding this block of code at the beginning of the proxy_pass function:
```
  if (cmd->argc == 1) {
    cmd->argc = 2;
    strcpy(cmd->argv[1],"");
  }

```

**Comment by Castaglia** [comment]
@ws0w could you try out [this PR](https://github.com/Castaglia/proftpd-mod_proxy/pull/85), see if it also addresses the issue?  Thanks!

**Comment by ws0w** [comment]
I've testes the referenced PR and it also fixed the problem.  Thanks.

**Comment by Castaglia** [comment]
Great, thanks!  Now merged to master.
